apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
  labels:
    app: message
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
      - name: message-ae
        image: zhuangtao/message-ae:latest
        ports:
        - containerPort: 10080
      - name: message-be
        image: zhuangtao/message-be:latest
        ports:
        - containerPort: 10079
      - name: message-au
        image: zhuangtao/message-au:latest
        ports:
        - containerPort: 5001
      - name: message-bu
        image: zhuangtao/message-bu:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: message
  namespace: default
spec:
  type: NodePort
  selector:
    app: message
  ports:
    # port: exposed to internal net
    # targetPort: port route into the pod
    # nodePort: exposed to external net
  - protocol: TCP
    name: tcp-bu-5000
    port: 5000 
    targetPort: 5000
    nodePort: 30000
  - protocol: TCP
    name: tcp-au-5001
    port: 5001 
    targetPort: 5001
    nodePort: 30001
